backend:
  name: git-gateway
  branch: master

media_folder: static/img

media_library:
  name: uploadcare
  config:
    publicKey: 0cd18d006f13d506a0c4

public_folder: /img

display_url: https://kogut-architects.netlify.com/

collections:
  - name: "pages"
    label: "Pages"
    files:
      # *********************************** Portfolio ***********************************
      - file: "src/pages/portfolio/index.md"
        label: "Portfolio"
        name: "portfolio"
        fields: 
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "portfolio-page" }
          - { 
              label: "Portfolio Types", 
              name: "portfolioTypes", 
              widget: "list",
              fields: [
                { label: "Name", name: "name", widget: "string" },
                {
                  label: "Jobs",
                  name: "jobs",
                  widget: "list",
                  fields: [
                    { label: "Name", name: "name", widget: "string" },
                    { 
                      label: "Image Gallery", 
                      name: "imageGallery", 
                      widget: "image",
                      media_library: {
                        config: { 
                          multiple: true
                        }
                      }
                    }
                  ]
                }
              ]
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      # *********************************** Profile ***********************************
      - file: "src/pages/profile/index.md"
        label: "Firm Profile"
        name: "profile"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "profile-page" }
          - { 
              label: "Employees", 
              name: "employees", 
              widget: "list",
              fields: [
                { label: "Name", name: "name", widget: "string" },
                { 
                  label: "Info", 
                  name: "info", 
                  widget: "object",
                  fields: [
                    { 
                      label: "Detail Type", 
                      name: "detailType", 
                      widget: "list",
                      fields: [
                        { label: "Title", name: "title", widget: "string" },
                        { label: "Details", name: "details", widget: "markdown" }
                      ]
                    }
                  ]
                }
              ]
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - { 
              label: "Image Gallery", 
              name: "imageGallery", 
              widget: "image",
              media_library: {
                config: { 
                  multiple: true
                }
              }
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
  - name: "headerAndFooter"
    label: "Header & Footer"
    files:
      - file: "src/pages/header/index.md"
        label: "Header"
        name: "header"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "header" }
          - {
              label: "Menu Items",
              name: "menuItems",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link Type", name: "linkType", widget: "select", options: ["internal", "external"] },
                  { label: "Link URL", name: "linkURL", widget: "string", hint: "Use a relative URL (e.g. /about) if the link is an internal link." },
                ],
            }
      - file: "src/pages/footer/index.md"
        label: "Footer"
        name: "footer"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "footer" }
          - {
              label: "Logo Image & Tagline",
              name: "logoImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                  { label: "Tagline", name: "tagline", widget: "string" },
                ],
            }